### ISSUE TITLE
The teal wallpaper contains a Hex color code

### ISSUE THREAD

**Issue by andikrueger** [pnp/media#5]
@StfBauer Great wallpapers!

The [teal](https://raw.githubusercontent.com/pnp/media/master/promo/wallpapers/parker-pnp-wallpaper-teal.png) one contains a color code on parkers head: #FF69B4

![image](https://user-images.githubusercontent.com/15608729/76083849-d1fa2000-5fae-11ea-93bd-7ab360e0a37e.png)

**Comment by koltyakov** [comment]
It's agent's Parker barcode. ;)

**Comment by StfBauer** [comment]
It was an easter egg especially for you @andikrueger - You get a special price!!! 😃💪

**Comment by StfBauer** [comment]
A new version without Agent parkers barcode.
